CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE),
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    tipo VARCHAR(255) NOT NULL,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id),
    CONSTRAINT ukkfsp0s1tflm1cwlj8idhqsad0 UNIQUE (email),
    CONSTRAINT usuarios_tipo_check CHECK (tipo IN ('ADMIN', 'PERSONAL', 'ALUNO'))
);

CREATE TABLE exercicios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE),
    nome VARCHAR(255) NOT NULL,
    descricao TEXT,
    ativo BOOLEAN NOT NULL,
    criado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT exercicios_pkey PRIMARY KEY (id)
);

CREATE TABLE vinculos_personal_aluno (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE),
    personal_id BIGINT NOT NULL,
    aluno_id BIGINT NOT NULL,
    criado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT vinculos_personal_aluno_pkey PRIMARY KEY (id),
    CONSTRAINT ukbp9ow5rgag2m3asi0gktnw1kd UNIQUE (aluno_id),
    CONSTRAINT fkg9p3e81jqyaf6idyf2l9erbi3 FOREIGN KEY (personal_id)
        REFERENCES usuarios (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION
        NOT DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT fkmbgryupgsbf0t84px42dapowl FOREIGN KEY (aluno_id)
        REFERENCES usuarios (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION
        NOT DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE treinos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE),
    nome VARCHAR(255) NOT NULL,
    descricao TEXT,
    aluno_id BIGINT NOT NULL,
    personal_id BIGINT NOT NULL,
    ativo BOOLEAN NOT NULL,
    criado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT treinos_pkey PRIMARY KEY (id),
    CONSTRAINT fk3aamwkuemlgsa1n5cca32hdh1 FOREIGN KEY (aluno_id)
        REFERENCES usuarios (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION
        NOT DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT fk8c9rrab2p3b5d2ux6bvctjrgh FOREIGN KEY (personal_id)
        REFERENCES usuarios (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION
        NOT DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE treino_exercicios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE),
    treino_id BIGINT NOT NULL,
    exercicio_id BIGINT NOT NULL,
    ordem INTEGER NOT NULL,
    series_planejadas INTEGER,
    repeticoes_planejadas VARCHAR(255),
    carga_planejada NUMERIC(10,2),
    observacoes TEXT,
    CONSTRAINT treino_exercicios_pkey PRIMARY KEY (id),
    CONSTRAINT uk_treino_exercicio_ordem UNIQUE (treino_id, ordem),
    CONSTRAINT fk67bnt5t8qesu66oc4e72tj1b0 FOREIGN KEY (treino_id)
        REFERENCES treinos (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION
        NOT DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT fktj1e59hhq2pojjaip7h8eykd4 FOREIGN KEY (exercicio_id)
        REFERENCES exercicios (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION
        NOT DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE execucoes_treino (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE),
    treino_id BIGINT NOT NULL,
    aluno_id BIGINT NOT NULL,
    treino_nome_snapshot VARCHAR(255) NOT NULL,
    iniciado_em TIMESTAMP WITH TIME ZONE NOT NULL,
    finalizado_em TIMESTAMP WITH TIME ZONE,
    duracao_segundos BIGINT,
    status VARCHAR(255) NOT NULL,
    observacoes TEXT,
    CONSTRAINT execucoes_treino_pkey PRIMARY KEY (id),
    CONSTRAINT execucoes_treino_status_check
        CHECK (status IN ('EM_ANDAMENTO', 'CONCLUIDO', 'CANCELADO')),
    CONSTRAINT fkhutnm67d8ypudcyv9ofiwuk90 FOREIGN KEY (treino_id)
        REFERENCES treinos (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION
        NOT DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT fkkoi8l5pag2ujsha2jemr0c429 FOREIGN KEY (aluno_id)
        REFERENCES usuarios (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION
        NOT DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE execucoes_exercicio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE),
    execucao_treino_id BIGINT NOT NULL,
    treino_exercicio_id BIGINT NOT NULL,
    exercicio_id_snapshot BIGINT NOT NULL,
    exercicio_nome_snapshot VARCHAR(255) NOT NULL,
    ordem_planejada INTEGER NOT NULL,
    series_planejadas INTEGER,
    repeticoes_planejadas VARCHAR(255),
    carga_planejada NUMERIC(10,2),
    observacoes_prescricao TEXT,
    duracao_segundos BIGINT,
    observacoes_aluno TEXT,
    CONSTRAINT execucoes_exercicio_pkey PRIMARY KEY (id),
    CONSTRAINT fk8matbrqcgvyx7m8st0wvft49t FOREIGN KEY (execucao_treino_id)
        REFERENCES execucoes_treino (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION
        NOT DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT fkscpfb48dolnuxev0ea854lh9r FOREIGN KEY (treino_exercicio_id)
        REFERENCES treino_exercicios (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION
        NOT DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE execucoes_series (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE),
    execucao_exercicio_id BIGINT NOT NULL,
    numero_serie INTEGER NOT NULL,
    repeticoes INTEGER,
    carga_utilizada NUMERIC(10,2),
    duracao_segundos BIGINT,
    concluida BOOLEAN NOT NULL,
    CONSTRAINT execucoes_series_pkey PRIMARY KEY (id),
    CONSTRAINT uk_execucao_exercicio_numero_serie
        UNIQUE (execucao_exercicio_id, numero_serie),
    CONSTRAINT fksp032bniwwg4xi97fwp294uqp FOREIGN KEY (execucao_exercicio_id)
        REFERENCES execucoes_exercicio (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION
        NOT DEFERRABLE INITIALLY IMMEDIATE
);
